### PR TITLE
Fix requestOptions in startChat

### PR DESCRIPTION
**Pull request by wong2**
Fix https://github.com/google-gemini/generative-ai-js/issues/227

In PR https://github.com/google-gemini/generative-ai-js/pull/144, the `requestOptions` of `GenerativeModel` is renamed to `_requestOptions`, but there's a `requestOptions` type declaration on the class, so TypeScript didn't catch the miss use of `requestOptions` instead of `_requestOptions` in the `startChat` method.

### CODE REVIEW

**Comment by hsubox76** [comment]
Thanks for catching this - two things:
1. there's been a refactor merged since you submitted this (the file moved)
2. run `yarn changeset` to add a changeset file (select "patch") to ensure this gets published

**Comment by wong2** [comment]
@hsubox76 I have rebased the branch.

However, I can't get `yarn changeset` working.

```
Internal Error: @google/generative-ai@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at $x.getCandidates (/Users/wong2/.cache/node/corepack/yarn/4.0.1/yarn.js:205:8149)
```

The error remains after I run `yarn install`.

Perhaps you can merge this and run the changeset command instead?

**Comment by hsubox76** [comment]
I think some files must be leftover after the rebase, it works fine for me on your fork. Anyway you can manually add the changeset file. If we do it in a separate PR it won't link to this PR properly. Create a file: `.changeset/real-windows-itch.md` (autogenerated name I got). Contents:

```
---
"@google/generative-ai": patch
---

Fix reference to `requestOptions` in `startChat`.
```

**Comment by wong2** [comment]
@hsubox76 I've added the changeset file

**Review by hsubox76 — DISMISSED** [review]

**Comment by hsubox76** [comment]
Are you able to run `yarn docs` to update the docs? If not, I can do it in a follow-up PR.

**Comment by wong2** [comment]
@hsubox76 Done!

**Comment by hsubox76** [comment]
I ran the integration tests locally as outside contributors don't have access to the API key secret - passed.

Thanks for the contribution, merging!

**Pull request merged**
