### PR TITLE
Fix missing usageMetadata in streamed aggregated response (#174)

### PR DESCRIPTION
**Pull request by jdoucy**
Fixes https://github.com/google-gemini/generative-ai-js/issues/174

### CODE REVIEW

**Comment by hsubox76** [comment]
Thank you! Can you add a changeset? (Run `yarn changeset` - select "patch".)

**Comment by jdoucy** [comment]
> Thank you! Can you add a changeset? (Run `yarn changeset` - select "patch".)

Done ✅

**Review by hsubox76 — APPROVED** [review]

**Comment by jdoucy** [comment]
@hsubox76 do you know when the next release is planned? 🙏

**Comment by hsubox76** [comment]
We have a feature to be released soon, likely tomorrow, so we will probably group this in with that.

**Comment by jdoucy** [comment]
> We have a feature to be released soon, likely tomorrow, so we will probably group this in with that.

Awesome 🙌 thx

**Pull request merged**
